# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
version: "3.8"
services:
  app_db:
    image: postgres
    restart: unless-stopped
    container_name: app_db
    hostname: app_db
    environment:
      POSTGRES_USER: postgres
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    entrypoint: >
      sh -c "sleep 10
      && alembic stamp head
      && alembic upgrade head
      && uvicorn src.main:app --host 0.0.0.0 --port 8055 --reload"
    depends_on:
       app_db:
         condition: service_healthy
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
